name: BuildCameraFramesSample
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
      runs-on: windows-latest

      steps:
      - uses: actions/checkout@v2
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1

      - name: MSBuild CS
        working-directory: Samples/CameraFrames/cs
        run: msbuild CameraFrames.sln /t:Build /p:Configuration=Debug;Platform=x64

      - name: MSBuild Cpp
        working-directory: Samples/CameraFrames/cpp
        run: msbuild CameraFrames.sln /t:Build /p:Configuration=Debug;Platform=x64
        
      - uses: actions/upload-artifact@v2
        with:
          name: CameraFrameSample
          path: Samples/CameraFrames/
