name: BuildCameraFramesSample
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
      runs-on: windows-latest

      steps:
      - uses: actions/checkout@v2
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1

      - name: MSBuild CS
        working-directory: ./
        run: msbuild Samples/CameraFrames/cs/CameraFrames.sln /t:Build /p:Configuration=Debug /p:Platform=x86 /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)\AppxPackages\\" /p:UapAppxPackageBuildMode=StoreUpload /p:AppxBundlePlatforms="$(Build.BuildPlatform)" /p:AppxBundle=Always

#       - name: MSBuild Cpp
#         working-directory: ./
#         run: msbuild Samples/CameraFrames/cs/CameraFrames.sln /t:Build /p:Configuration=Debug /p:Platform=x86
        
      - uses: actions/upload-artifact@v2
        with:
          name: CameraFrameSample
          path: Samples/CameraFrames/
