name: BuildCameraFramesSample
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
      runs-on: windows-latest

      steps:
      - uses: actions/checkout@v2
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1
      
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: 'latest'
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      - name: NuGet Restore
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./
        run: nuget restore Samples/CameraFrames/cs/CameraFrames.sln

      - name: MSBuild CS
        working-directory: ./
        run: msbuild Samples/CameraFrames/cs/CameraFrames.sln /t:Build /p:Configuration=Debug /p:Platform=x86

#       - name: MSBuild Cpp
#         working-directory: ./
#         run: msbuild Samples/CameraFrames/cs/CameraFrames.sln /t:Build /p:Configuration=Debug /p:Platform=x86
        
      - uses: actions/upload-artifact@v2
        with:
          name: CameraFrameSample
          path: Samples/CameraFrames/
